# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "33094b002ce3715605a6827d5ed86f89"
name = "checkout-extension"
handle = "checkout-extension-644"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "checkoutstore314.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
